### ISSUE TITLE
get_console_width() failure can result in 'Inappropriate ioctl for device'

### ISSUE THREAD

**Issue by accwebs** [avirshup/DockerMake#19]
If 'stty size' fails in get_console_width(), the following message may be written to stderr:
'stty: standard input: Inappropriate ioctl for device' 

This seems to show up in build systems (in my case Jenkins) resulting in a lot of instances of this error showing up in the build output.

It looks like this is a common problem with other Python programs that check the console width in this way. Pull request coming soon.

**Comment by avirshup** [comment]
Fixed in release 0.5.6. Thanks!
