### ISSUE TITLE
Reuse existing dockerfiles

### ISSUE THREAD

**Issue by kolis** [avirshup/DockerMake#2]
It would be nice to be able to reuse Dockerfiles in the build tag of the DockerMake.yaml. Or use a new tag eg
build_script: path/to/Dockerfile

Eg for reusing existing files, and to get proper syntax highlighting in the editor

**Comment by yoyonel** [comment]
Hi Kolis! 
My pull request implement this option :)
https://github.com/avirshup/DockerMake/pull/9

**Comment by avirshup** [comment]
I've actually thought about this one a lot, but have decided that I really always want the base image to be clearly defined in the DockerMake.yml file.

HOWEVER, I like the idea of allowing the "FROM" field to be a path to a Dockerfile. I don't personally have a use case for this, but would gratefully accept a PR for it :)

**Comment by 2014qirong** [comment]
can be automatic rebuild depency image ?

**Comment by avirshup** [comment]
@2014qirong - yes, good idea. Now implementing this in #26

**Comment by avirshup** [comment]
OK, as of 0.5.7, you can now use `FROM_DOCKERFILE: [path]` in the place of `FROM: [docker image]`
