### ISSUE TITLE
Build arg to use as an variable in makefile

### ISSUE THREAD

**Issue by epcim** [avirshup/DockerMake#45]
Recently ARGs support was added and it's missing in README.

Could you also support that build ARGs may be used to pre-process the yaml? Example:
```         
# --build-arg os_codename=stretch

debian-{{os_codename}:
  FROM: debian:{{os_codename}}
```

**Comment by avirshup** [comment]
> Recently ARGs support was added and it's missing in README.
Done, should appear in master soon. Thanks!

> Could you also support that build ARGs may be used to pre-process the yaml?
Will discuss in #44
