### ISSUE TITLE
--all option stops when target has no FROM defined

### ISSUE THREAD

**Issue by epcim** [avirshup/DockerMake#52]
When --all option is used, targes without FROM should be skipped (or we have to decorate what targets are assumed as "all"). Otherwise they fail and workaround is ugly:
```
IGNORE="(base|common)"
        docker-make --list |awk '/*/{print $2}'| grep -v "${IGNORE}" | xargs -n1 -I% docker-make % 
```

Reminds me that would be nice to have the option to convert severe errors to warnings. So one target fails but other are still building.

**Comment by avirshup** [comment]
Have finally circled back around to this project :)

Thanks for finding this issue, it's a good one. I believe it should be fixed as of aeac230fd5ab468d806bf42b120aa97f91eb40a2

However, I might not have hit all the edge cases, please do open another issue if it's still broken. I promise I'll get to it within ... well, my turnaround appears to be a few months.
